# Generated by Django 5.1.3 on 2025-03-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_alarm_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserData',
        ),
    ]
