# Generated by Django 5.1.3 on 2025-03-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_alarm_app', '0002_rename_user_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accelerometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('xAcceleration', models.IntegerField()),
                ('yAcceleration', models.IntegerField()),
                ('zAcceleration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gyroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('xAccelerationR', models.IntegerField()),
                ('yAccelerationR', models.IntegerField()),
                ('zAccelerationR', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeartRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('ECG', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('temperature', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('userID', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
