# Generated by Django 5.1.3 on 2025-04-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergy_alarm_app', '0004_remove_useridentification_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accelerometer',
            old_name='xAcceleration',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='accelerometer',
            old_name='yAcceleration',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='accelerometer',
            old_name='zAcceleration',
            new_name='z',
        ),
        migrations.RenameField(
            model_name='gyroscope',
            old_name='xAccelerationR',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='gyroscope',
            old_name='yAccelerationR',
            new_name='y',
        ),
        migrations.RenameField(
            model_name='gyroscope',
            old_name='zAccelerationR',
            new_name='z',
        ),
    ]
